### ISSUE TITLE
Problem during the implementation of the project and the use of first commands

### ISSUE THREAD

**Issue by SullivanMAXWELL** [LoicGoyet/frontlab#6]
Hey, my problem is the following :

when I downloaded the zip file, and that I renome to start my project , So i go to refer myself to the DOC , however, when I start to use the first command `run npm make- dev`  I have a lot of errors and warning for exemple : 

```
npm ERR ! Failed front-lab@1.0.0 at the make- dev script ' npm install && && bower install compiles gulp .
```

and much more , so I checked that I had "npm" installed, this is the case, and I told myself that there was nothing to manage in terms gulp since the file was already present .

Could you help me to identify the problem, please?

**Comment by LoicGoyet** [comment]
@SullivanMAXWELL 
There is nothing about gulp into this, gulp is a node package, and this is the node package manager that does not work, so gulp issues comes after a working usage of npm.

Just is the typo into your issue (`run npm make- dev` instead of `run npm make-dev`) is a typo from this very issue writting or did you type the wrong command ?

**Comment by SullivanMAXWELL** [comment]
Oh sorry I just mistake in the description , I have used the correct command : "npm run make-dev" ! So I have again my problem

**Comment by LoicGoyet** [comment]
Alright it seems that not changing the node package `name` could cause issues.

**Comment by SullivanMAXWELL** [comment]
Ok, man, my problem is resolved, Thank to have take the time to answer me.
Have a nice week !
